// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "tsx prisma/seed.ts && tsx prisma/seed-workforce.ts && tsx prisma/seed-assets.ts && tsx prisma/seed-materials.ts && tsx prisma/seed-subcontracts.ts && tsx prisma/seed-operations.ts",
  },
  datasource: {
    url: process.env["DATABASE_URL"],
  },
});
